### PR TITLE
Final Changes to video saving 

### PR DESCRIPTION
**Pull request by Prakash19921206**
fixed wrong fps calculation . and improved video saving part.
input video & camera will be saved properly. tested on few cases for both video & web camera, no issues found.

### CODE REVIEW

**Comment by thtrieu** [comment]
@Prakash19921206  Why did you close this PR? I cannot merge a closed PR.

**Comment by Prakash19921206** [comment]
there was conflict in PR, making changes..will create reopen

**Comment by Prakash19921206** [comment]
i don't know how to resolve this conflict.
@thtrieu , u can find proper code [here ](https://github.com/Prakash19921206/darkflow/blob/master/net/help.py)
 this code we need to use in help.py
what changes i need to make?  
if possible can you make changes accordingly and merge PR?

**Comment by Prakash19921206** [comment]
@thtrieu , i don't know how to resolve this conflict.

its saying in master its 
```
fps = round(camera.get(cv2.CAP_PROP_FPS))
        height, width, _ = frame.shape
```
where as i added 

```
 if file == 0:
         fps = 1 / get_fps(self, frame)
         if fps < 1:
                fps = 1
        else:
            fps = round(camera.get(cv2.CAP_PROP_FPS))
```

what changes i need to make?  
if possible can you make changes accordingly and merge PR?

**Comment by borasy** [comment]
Awesome, everything looks great.

**Comment by Prakash19921206** [comment]
@thtrieu , i don't know how the definition `get_fps `was left out..while creating PR my fork had it.. GitHub did a mistake. somehow it removed it from my york also! even though i didn't pull anything from this repository 
can you add this function in [net/help.py](https://github.com/thtrieu/darkflow/blob/master/net/help.py) yourself?

```
def get_fps(self,frame):
    elapsed = int()
    start = timer()
    preprocessed = self.framework.preprocess(frame)
    feed_dict = {self.inp: [preprocessed]}
    net_out = self.sess.run(self.out, feed_dict)[0]
    processed = self.framework.postprocess(net_out, frame, False)
    return timer() - start
```

**Comment by thtrieu** [comment]
I did it.

**Pull request merged**
