### PR TITLE
Camera-less mode to run server-side or Docker

### PR DESCRIPTION
**Pull request by loretoparisi**
To enable server-side processing of a video input, when the input is a file. 
When using `flow` with a video file input like

```
./flow --model bin/yolo.cfg --load bin/yolo.weights --demo samples/video_1.avi --gpu .8 --saveVideo
```

It avoids to create a `OpenCV` window object, letting the processing to run on a server and on a image container (like `Docker`).
See comment https://github.com/thtrieu/darkflow/issues/156#issuecomment-297993004 for further info.

### CODE REVIEW

**Comment by borasy** [comment]
Shouldn't you put a FLAG to let people choose whether they want the window to show or not? It seems like you turn the camera option completely off.

**Comment by loretoparisi** [comment]
@borasy Yes I think an optional flag could help. Now it disable the camera `Window` when a file is passed, otherwise it will work as usual.

**Comment by abagshaw** [comment]
@loretoparisi This looks like a neat addition - (looks like there are some conflicting changes that need resolved before this can be merged though).

There is already a `--saveVideo` flag that saves the processed video. I think it would make sense not to show the window if that flag is set to true, but if it is false then the window should be shown because otherwise there will be no output at all. Someone may want to process a file and still see the output visually.

**Comment by loretoparisi** [comment]
@abagshaw Yes Maybe I can add a flag `noCameraWindow` that set to `true`, defaults to `false` will do the same?

**Comment by abagshaw** [comment]
@loretoparisi I think that makes things unnecessarily complicated. If `--saveVideo` is true I think it's perfectly safe to assume that the user doesn't need a window to be shown. If it's false than clearly they do need a window. Your call - just nice to keep the number of flags to a minimum if possible 😃

**Comment by loretoparisi** [comment]
@abagshaw I perfectly agree to only have `--saveVideo` as the only option to handle both video file input and the camera window off, that makes a lot of sense, and it was my initial idea. So it should go as it is now.

**Comment by abagshaw** [comment]
Sorry - maybe I was confused. Some of the lines seemed to suggest to me that it was just checking to see if a file was specified to then possibly run the code specific to window management. See https://github.com/thtrieu/darkflow/pull/207/files#diff-4129b03c4d45751334b487775798c80dR132 (looks to me like the windows are only closed if a file is present - no mention of `saveVideo` there?)

Maybe I'm just confused though. Either way if you could resolve whatever conflicts there are for this PR that would be great so it can get merged.

**Comment by loretoparisi** [comment]
I did the merge with the recent update.

**Comment by relh** [comment]
I use this as my docker container start command to run without Xwindows problems:
(Main is a flask server hooked into darkflow)

```
#!/bin/bash
# Starts XWindows Headless
Xvfb :1 -screen 0 1024x768x16 +extension RANDR &
# Executes Script
python3 main.py
```

**Comment by loretoparisi** [comment]
Thanks, this will attach the host screen to the docker container image, so it works fine when the host is a workstation with a screen, but on a server, there is no xwindow and screen device to attach the container screen 0.By the way your solution works fine on MS Windows as well as host. Do not know if it will work on macOS as host.
		

		Ottieni Outlook per iOS
	





On Thu, May 25, 2017 at 2:45 PM +0200, "Richard Higgins" <notifications@github.com> wrote:












I use this as my docker container start command to run without Xwindows problems:

(Main is a flask server hooked into darkflow)
#!/bin/bash
# Starts XWindows Headless
Xvfb :1 -screen 0 1024x768x16 +extension RANDR &
# Executes Script
python3 main.py

**Comment by abagshaw** [comment]
@loretoparisi Another thought I just had - the functionality for video processing is clearly beyond just for demo purposes (as far as I am concerned). Does it still make sense to have this run with the `--demo` flag - or should the `--demo` flag be relegated for processing a live camera feed and some other flag be created for video file processing?

**Comment by loretoparisi** [comment]
@abagshaw yes in fact I think the `--demo` is unnecessary for this purposes, and as you said it could be used to use the live camera instead of video files processing.
What is missing to go on with the PR?

**Comment by abagshaw** [comment]
@loretoparisi Everything looks good to me, it's just up to @thtrieu to take a look at this and merge it. I think he's pretty busy right now so that's probably why this is taking a while.

**Pull request merged**
