### PR TITLE
pascal annotation parsing code

### PR DESCRIPTION
**Pull request by hello072**
In my case, var "annotations" has some wrong xmllist.... I cannot find solution but just modify using glob python package.. I also modify parsing part using xml package... May be more simple

### CODE REVIEW

**Comment by thtrieu** [comment]
Hi, thanks for providing a much more elegant code. I tested it and found a bug regarding a mixed use of spaces and tab for indentation.

Could you fix this and I'll merge :)

**Comment by thtrieu** [comment]
A few more suggestions:

1. Since the function `parse` and `int` is no longer needed, please delete it.
2. `pp()` should be brought outside of the main function and renamed `_pp()`

**Comment by thtrieu** [comment]
I did this myself, thanks :)

**Comment by hello072** [comment]
WoW..... It's my first communication with others in github!!!! Thanks for considering my suggestions!!!

**Pull request closed without merging**
