### PR TITLE
Providing more TF trainer options

### PR DESCRIPTION
**Pull request by lilohuang**
1. Add "decay" option for rmsprop optimizer
2. Supply "decay" and "momentum" on build_train_op if need

### CODE REVIEW

**Comment by onurbarut** [comment]
hi, is there momentum option? I couldn't set --trainer momentum .9, it gives error.

**Comment by lilohuang** [comment]
No, I think. This PR didn't be merged in time so I close it. You can apply my code changes on your  repository, and I can create PR again if it does work for you. Thanks!

**Comment by lilohuang** [comment]
No, I don't think so. This PR didn't be merged in time so I close it. You can apply my code changes on your repository, and I can create PR again if it does work for you. Thanks.

**Comment by lilohuang** [comment]
No, I don't think so. This PR didn't be merged in time so I closed it. You can apply my code changes on your repository, and I will create PR again if it does work for you. Thanks.

**Pull request closed without merging**
