### PR TITLE
FPS and a small bug

### PR DESCRIPTION
**Pull request by borasy**
Using the fps from original input video as output video fps and fix small bug videoWriter.release() is referred before assigned when savevideo is false.

### CODE REVIEW

**Comment by Prakash19921206** [comment]
@thtrieu , there are still some changes needs to be done..
as per current merge , video will not be saved via webcam.. please read all comments [here](https://github.com/thtrieu/darkflow/pull/126)
only change needed is (with respect to previous commit),
in help.py
change line 77 (`fps = get_fps(self, frame)`)  to
```
if file == "camera" :
    fps = get_fps(self, frame)
else:
    fps = round(camera.get(cv2.CAP_PROP_FPS))
```

Note: in current merge , `get_fps `function is removed.

**Comment by thtrieu** [comment]
where is the function `get_fps`?

**Comment by Prakash19921206** [comment]
https://github.com/thtrieu/darkflow/pull/126/files

scroll to last in above link

**Comment by borasy** [comment]
@thtrieu please refer to our comments [here](https://github.com/thtrieu/darkflow/pull/126)

**Pull request merged**
