### PR TITLE
Enable loading from .pb file

### PR DESCRIPTION
**Pull request by abagshaw**
Changes to allow darkflow to load from a `.pb` file. Now when using `--savepb` a `.meta` file is also generated which is a JSON dump of the `.meta` variable (I talked about this here: https://github.com/thtrieu/darkflow/issues/143#issuecomment-292794853)

Two new flags are were created `pbLoad` and `metaLoad` that allow for loading from the `.pb` file and `.meta` file instead of a `.cfg` and `.weights` or checkpoint. Also this eliminates the need to have a labels file tagging along as everything necessary for post-processing is contained in the `.meta` file

### CODE REVIEW

**Comment by thtrieu** [comment]
This is great!

Just that I need to see some use cases of loading from .pb. In fact, I did a quick search in the Issues Track, it seems nobody is interested in loading from `.pb` file. Am I missing something? Just that I am feeling the repo is getting more and more cumbersome.

**Comment by abagshaw** [comment]
Looks like at least one person: https://github.com/thtrieu/darkflow/issues/184#issuecomment-298239713

The main thing is that this is part of hopefully getting quantization to work. Tensorflow can quantize 32bit weights in `.pb` files to 8bit to save space, RAM usage when running inference and a little computation time. Once a `.pb` file is optimized it can be loaded back into darkflow for inference.

Also:
1. Makes things a little more manageable (you only have to carry around `.meta` and `.pb` file and don't have to worry about what labels file to load because it's all stored in the `.meta` file)
2. Speeds up initialization - you don't have to build the graph from scratch.

I agree - this is more of a fringe feature..but I do think it's helpful and not just adding bloat.

**Comment by venuktan** [comment]
+1 on this please 🙏

**Comment by abagshaw** [comment]
@thtrieu Think we could get this pulled soon? :)

**Comment by ydzhang12345** [comment]
Really really need this! Actually we want to modify the generated pb file and then load back to the system to see the performance. Will be really appreciated

**Pull request merged**
