### PR TITLE
return_predict also returns color index (colorIdx)

### PR DESCRIPTION
**Pull request by akashjobanputra**
Color Index for drawing different colored bounding boxes according to the id

### CODE REVIEW

**Comment by ttorkar** [comment]
I'm interested in what you're doing with the color index, care to share? 👍

**Comment by akashjobanputra** [comment]
@ttorkar, sure. I'll share as soon as I reach at work.

**Comment by abagshaw** [comment]
@akashjobanputra Looks interesting. I'm a little conflicted if this is adding unnecessary information to the output (as you can just reference the output label against all labels to get the index) - but I suppose it's fairly insignificant.

Either way I think it would be better to use a more appropriate descriptor like `labelindex` instead of `colorIdx`. You can use the `labelindex` to generate colours, but that's not what the number really represents.

**Comment by akashjobanputra** [comment]
As per the points you mentioned in #529, I do agree that the giving out color representation is not a part of darkflow's purpose. I thought to use what darkflow was already doing internally.

Thanks for the response. I'll be managing color codes in the script that uses `return_predict()`.

**Pull request closed without merging**
